/*----- PROTECTED REGION ID(WebSocketDS_cliClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        WebSocketDS_cliClass.h
//
// description : Include for the WebSocketDS_cli root class.
//               This class is the singleton class for
//                the WebSocketDS_cli device class.
//               It contains all properties and methods which the 
//               WebSocketDS_cli requires only once e.g. the commands.
//
// project :     WebSocket access to tango device-server attributes, pipes and commands
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef WebSocketDS_cliClass_H
#define WebSocketDS_cliClass_H

#include <tango.h>
#include <WebSocketDS_cli.h>


/*----- PROTECTED REGION END -----*/	//	WebSocketDS_cliClass.h


namespace WebSocketDS_ns
{
/*----- PROTECTED REGION ID(WebSocketDS_cliClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	WebSocketDS_cliClass::classes for dynamic creation

/**
 *	The WebSocketDS_cliClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  WebSocketDS_cliClass : public Tango::DeviceClass
#else
class WebSocketDS_cliClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(WebSocketDS_cliClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	WebSocketDS_cliClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static WebSocketDS_cliClass *init(const char *);
		static WebSocketDS_cliClass *instance();
		~WebSocketDS_cliClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		WebSocketDS_cliClass(string &);
		static WebSocketDS_cliClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	WebSocketDS_cli_H
